### ISSUE TITLE
Make connection test completely

### ISSUE THREAD

**Issue by peter279k** [halfer/php-mysql-circleci#1]
As title, I think we can consider using the PHPUnit test to make database connection test completed.

@halfer. Once this issue is accepted, I can work on this and please add `#orbtoberfest` on this issue because of the [hacktoberfest circleci](https://hacktoberfest.circleci.com) :).

**Comment by halfer** [comment]
Hi @peter279k. Thanks for raising an issue, an apologies for the delay - I don't sign into GH very often.

I think PHPUnit may be overkill here. The point of the `connect.php` script is just to show that database connections work, and the point of the whole repo is to give folks a helping hand with MySQL/PHP in CircleCI. It isn't really test automation in the normal sense i.e. with a finished application.

**Comment by peter279k** [comment]
Hi @halfer, thanks for your reply.

I think it's fine to use this current testing approach on `CircleCI`.

Closed this issue due to your explanation :).
